#!/bin/sh

set -e
export CC=gcc

command -v bundle >/dev/null 2>&1 || { echo >&2 "Bundler required but not found: gem install bundler"; exit 1; }

echo "==> Installing gem dependencies…"

bundle install --local --binstubs --path vendor/cache "$@"
