#!/bin/sh

set -e
export CC=gcc

command -v bundle >/dev/null 2>&1 || { echo >&2 "Bundler required but not found: gem install bundler"; exit 1; }

echo "==> Installing gem dependencies…"
bundle check --path vendor/cache 2>&1 || {
  bundle install --path vendor/cache
}
