#!/bin/sh
# Usage: script/cibuild
# CI build script
#
set -e

# GC customizations
export RUBY_GC_MALLOC_LIMIT=79000000
export RUBY_GC_HEAP_INIT_SLOTS=800000
export RUBY_HEAP_FREE_MIN=100000
export RUBY_HEAP_SLOTS_INCREMENT=400000
export RUBY_HEAP_SLOTS_GROWTH_FACTOR=1

export PATH="/usr/share/rbenv/shims:$PATH"
export RACK_ROOT=$(cd "$(dirname $0)"/.. && pwd)
export RACK_ENV="test"
export RAILS_ENV="test"
export RBENV_VERSION="2.1.6-github"

# clean out the ruby environment
export RUBYLIB=
export RUBYOPT=

# bootstrap gem environment changes
cd "$RACK_ROOT"
echo 'Bootstrapping gems...'
script/bootstrap

echo "==> Running tests…"
bundle exec rake test
