#!/usr/bin/env ruby

require 'fileutils'
require 'tmpdir'
require 'nokogiri'

IS_ENTERPRISE = true

ERROR_MESSAGE = """
Error: Run the script like this: bundle exec script/enterprise-cutter [DATE] [VERSION]
e.g. bundle exec script/enterprise-cutter 2014-07-08 11.10.340
"""

if ARGV.length == 0
    abort "\n#{ERROR_MESSAGE}\n\n"
elsif ARGV.length > 2
    abort "\n#{ERROR_MESSAGE}\n\n"
end

date = ARGV[0].dup # yyyy-mm-dd, like, 2014-07-08
version = ARGV[1].dup # like, 11.10.340

BRANCH_NAME = "add-#{version}-docs"

%x(git checkout gh-pages)
%x(git pull origin gh-pages)

%x(git checkout -b #{BRANCH_NAME})

temp_dir = Dir.mktmpdir
begin
  %x(git checkout `git rev-list -n 1 --before="#{date}" gh-pages`)
  %x(cp -r * #{temp_dir})
  %x(git checkout #{BRANCH_NAME})
  version.sub!(/enterprise-/, '')
  FileUtils.mkdir_p("enterprise/#{version}")
  %x(cp -r #{temp_dir}/* enterprise/#{version})

  # we need to point links not to the root, but to the enterprise version root
  # for assets and links
  Dir.glob("enterprise/#{version}/**/*.html") do |html_file|
    doc = Nokogiri::HTML(File.read(html_file))
    doc.search('body').first.add_class('enterprise')
    doc.css('a').each do |a|
      a['href'] = "/enterprise/#{version}#{a['href']}" if a['href'] =~ /^\//
    end
    doc.css('link').each do |link|
      link['href'] = "/enterprise/#{version}#{link['href']}" if link['href'] =~ /^\//
    end
    doc.css('script').each do |script|
      script['src'] = "/enterprise/#{version}#{script['src']}" if script['src'] =~ /^\//
    end
    doc.css('img').each do |img|
      img['src'] = "/enterprise/#{version}#{img['src']}" if img['src'] =~ /^\//
    end
    doc.search('//*[@class="not-enterprise"]').remove
    File.open(html_file, 'w') { |file| file.write(doc.to_html) }
  end

  Dir.glob("enterprise/#{version}/**/*.css") do |css_file|
    contents = File.read(css_file)
    contents.gsub!(/url\(\/shared/, "url(/enterprise/#{version}/shared")
    File.open(css_file, 'w') { |file| file.write(contents) }
  end

  %x(git add enterprise)
  %x(git commit -m "Added enterprise-#{version} files")
ensure
  FileUtils.remove_entry_secure temp_dir
end

puts "\n\nOkay! Feel free to `git push #{BRANCH_NAME}` if you like."
