#!/bin/sh

echo ""
echo ""
echo "*********************************************************************"
echo "****** Starting guard. In another window, run adsf -r output  *******"
echo "************* Yes, really: http://git.io/GFd6UQ *********************"
echo "*********************************************************************"
echo ""
echo ""

if [ "--enterprise" == "$1" ]; then
  echo '~~~~ Enterprise Mode Activated ~~~~'
  ENTERPRISE=true bundle exec guard
else
  bundle exec guard
fi
