#!/usr/bin/env bash

ulimit -n 2048

script/bootstrap

if [ -z "$1" ]
  then
    DEV_MODE=true npm run gulp
  else
    script/enterprise-backport $1
    mv -f enterprise output
    npm run gulp server
fi
