#!/bin/sh

echo ""
echo ""
echo "*********************************************************************"
echo "****** Starting guard. In another window, run adsf -r output. *******"
echo "************* Yes, really: http://git.io/GFd6UQ *********************"
echo "*********************************************************************"
echo ""
echo ""

bundle exec guard
